version: "3.3"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  myapi:
    build:
      context: "./service"
    volumes:
      - "./service:/app"
    environment:
      - "ADMIN_APP_ORIGIN=http://jonathanearlio"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapi.rule=Host(`api.jonathanearlio.localhost`)"
      - "traefik.http.routers.myapi.entrypoints=web"
  
  jonathanearlio:
    build:
      context: "./jonathanearl.io"
    volumes:
      - "./jonathanearl.io:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jonathanearlio.rule=Host(`jonathanearlio.localhost`)"
      - "traefik.http.routers.jonathanearlio.entrypoints=web"
