name: deploy-to-s3

on:
  push:
    branches: [ $default-branch ]

jobs:
  deploy-to-s3:
    name: Deploy to S3

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test --if-present
    - run: aws s3 sync s3://jonathanearl.io ./public --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'